# Generated by Django 4.2.7 on 2024-03-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the album', max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Release year of the album')),
                ('main_cover', models.ImageField(help_text='Main cover of the album', upload_to='album_covers/')),
                ('tracklist', models.JSONField(help_text='List of songs in the album in JSON format')),
                ('comments', models.TextField(help_text='Additional comments about the album')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the artist', max_length=100)),
                ('photo', models.ImageField(help_text="Artist's photo", upload_to='artist_photos/')),
                ('review', models.TextField(help_text='Review of the artist')),
                ('youtube_link', models.URLField(help_text="Artist's YouTube link")),
                ('spotify_link', models.URLField(help_text="Artist's Spotify link")),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(help_text='Title of the song', max_length=100)),
                ('lyrics', models.TextField(help_text='Lyrics of the song')),
                ('youtube_link', models.URLField(help_text='YouTube link of the song')),
                ('spotify_link', models.URLField(help_text='Spotify link of the song')),
                ('album', models.ForeignKey(help_text='Album to which the song belongs', on_delete=django.db.models.deletion.CASCADE, to='frontend.album')),
                ('artist', models.ForeignKey(help_text='Artist of the song', on_delete=django.db.models.deletion.CASCADE, to='frontend.artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(help_text='Artist of the album', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='frontend.artist'),
        ),
    ]
