# Generated by Django 4.2.7 on 2024-03-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_url',
            field=models.URLField(help_text='URL of the album cover', null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='featured_artists',
            field=models.ManyToManyField(blank=True, related_name='featured_albums', to='frontend.artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo_url',
            field=models.URLField(help_text="URL of the artist's photo", null=True),
        ),
    ]
