# Generated by Django 4.2.7 on 2024-03-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_album_cover_url_album_featured_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='spotify_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotify_link',
        ),
        migrations.AddField(
            model_name='album',
            name='deezer_album_link',
            field=models.URLField(help_text="Albums's Deezer link", null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='deezer_link',
            field=models.URLField(help_text="Artist's Deezer link", null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_link',
            field=models.URLField(help_text="Artist's Instagram link", null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='deezer_link',
            field=models.URLField(help_text='Deezer link of the song', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(help_text='Name of the artist', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube_link',
            field=models.URLField(help_text="Artist's YouTube link", null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_link',
            field=models.URLField(help_text='YouTube link of the song', null=True),
        ),
    ]
