# Generated by Django 4.2.7 on 2024-03-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_artist_spotify_link_remove_song_spotify_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='featured_artists',
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram_link',
            field=models.URLField(blank=True, help_text="Artist's Instagram link", null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube_link',
            field=models.URLField(blank=True, help_text="Artist's YouTube link", null=True),
        ),
    ]
