# Generated by Django 4.2.7 on 2024-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_album_featured_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='main_cover',
            field=models.ImageField(blank=True, help_text='Main cover of the album', null=True, upload_to='album_covers/'),
        ),
    ]
