# Generated by Django 4.2.7 on 2024-03-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_artist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, help_text="Artist's photo", null=True, upload_to='artist_photos/'),
        ),
    ]
