# Generated by Django 4.2.7 on 2024-03-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_artist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube link of the song', null=True),
        ),
    ]
